// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gonet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item used across all 4 RPC types
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_gonet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_gonet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_gonet_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Item) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_gonet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gonet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_gonet_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_gonet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gonet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_gonet_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_gonet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gonet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_gonet_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListItemsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SendItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount int32                  `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendItemsResponse) Reset() {
	*x = SendItemsResponse{}
	mi := &file_gonet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendItemsResponse) ProtoMessage() {}

func (x *SendItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gonet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendItemsResponse.ProtoReflect.Descriptor instead.
func (*SendItemsResponse) Descriptor() ([]byte, []int) {
	return file_gonet_proto_rawDescGZIP(), []int{4}
}

func (x *SendItemsResponse) GetReceivedCount() int32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *SendItemsResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ExchangeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeMessage) Reset() {
	*x = ExchangeMessage{}
	mi := &file_gonet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeMessage) ProtoMessage() {}

func (x *ExchangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gonet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeMessage.ProtoReflect.Descriptor instead.
func (*ExchangeMessage) Descriptor() ([]byte, []int) {
	return file_gonet_proto_rawDescGZIP(), []int{5}
}

func (x *ExchangeMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ExchangeMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExchangeMessage) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_gonet_proto protoreflect.FileDescriptor

const file_gonet_proto_rawDesc = "" +
	"\n" +
	"\vgonet.proto\x12\x05gonet\"\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x0fGetItemResponse\x12\x1f\n" +
	"\x04item\x18\x01 \x01(\v2\v.gonet.ItemR\x04item\"@\n" +
	"\x10ListItemsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"T\n" +
	"\x11SendItemsResponse\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x05R\rreceivedCount\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"_\n" +
	"\x0fExchangeMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence2\xf3\x01\n" +
	"\fGonetService\x128\n" +
	"\aGetItem\x12\x15.gonet.GetItemRequest\x1a\x16.gonet.GetItemResponse\x123\n" +
	"\tListItems\x12\x17.gonet.ListItemsRequest\x1a\v.gonet.Item0\x01\x124\n" +
	"\tSendItems\x12\v.gonet.Item\x1a\x18.gonet.SendItemsResponse(\x01\x12>\n" +
	"\bExchange\x12\x16.gonet.ExchangeMessage\x1a\x16.gonet.ExchangeMessage(\x010\x01B\x0fZ\rgonet/grpc/pbb\x06proto3"

var (
	file_gonet_proto_rawDescOnce sync.Once
	file_gonet_proto_rawDescData []byte
)

func file_gonet_proto_rawDescGZIP() []byte {
	file_gonet_proto_rawDescOnce.Do(func() {
		file_gonet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gonet_proto_rawDesc), len(file_gonet_proto_rawDesc)))
	})
	return file_gonet_proto_rawDescData
}

var file_gonet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gonet_proto_goTypes = []any{
	(*Item)(nil),              // 0: gonet.Item
	(*GetItemRequest)(nil),    // 1: gonet.GetItemRequest
	(*GetItemResponse)(nil),   // 2: gonet.GetItemResponse
	(*ListItemsRequest)(nil),  // 3: gonet.ListItemsRequest
	(*SendItemsResponse)(nil), // 4: gonet.SendItemsResponse
	(*ExchangeMessage)(nil),   // 5: gonet.ExchangeMessage
}
var file_gonet_proto_depIdxs = []int32{
	0, // 0: gonet.GetItemResponse.item:type_name -> gonet.Item
	1, // 1: gonet.GonetService.GetItem:input_type -> gonet.GetItemRequest
	3, // 2: gonet.GonetService.ListItems:input_type -> gonet.ListItemsRequest
	0, // 3: gonet.GonetService.SendItems:input_type -> gonet.Item
	5, // 4: gonet.GonetService.Exchange:input_type -> gonet.ExchangeMessage
	2, // 5: gonet.GonetService.GetItem:output_type -> gonet.GetItemResponse
	0, // 6: gonet.GonetService.ListItems:output_type -> gonet.Item
	4, // 7: gonet.GonetService.SendItems:output_type -> gonet.SendItemsResponse
	5, // 8: gonet.GonetService.Exchange:output_type -> gonet.ExchangeMessage
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gonet_proto_init() }
func file_gonet_proto_init() {
	if File_gonet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gonet_proto_rawDesc), len(file_gonet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gonet_proto_goTypes,
		DependencyIndexes: file_gonet_proto_depIdxs,
		MessageInfos:      file_gonet_proto_msgTypes,
	}.Build()
	File_gonet_proto = out.File
	file_gonet_proto_goTypes = nil
	file_gonet_proto_depIdxs = nil
}
