// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: gonet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GonetService_GetItem_FullMethodName   = "/gonet.GonetService/GetItem"
	GonetService_ListItems_FullMethodName = "/gonet.GonetService/ListItems"
	GonetService_SendItems_FullMethodName = "/gonet.GonetService/SendItems"
	GonetService_Exchange_FullMethodName  = "/gonet.GonetService/Exchange"
)

// GonetServiceClient is the client API for GonetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GonetServiceClient interface {
	// 1. Unary — single request, single response
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	// 2. Server Streaming — single request, stream of responses
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error)
	// 3. Client Streaming — stream of requests, single response
	SendItems(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Item, SendItemsResponse], error)
	// 4. Bidirectional Streaming — stream both directions simultaneously
	Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExchangeMessage, ExchangeMessage], error)
}

type gonetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGonetServiceClient(cc grpc.ClientConnInterface) GonetServiceClient {
	return &gonetServiceClient{cc}
}

func (c *gonetServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, GonetService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gonetServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Item], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GonetService_ServiceDesc.Streams[0], GonetService_ListItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListItemsRequest, Item]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonetService_ListItemsClient = grpc.ServerStreamingClient[Item]

func (c *gonetServiceClient) SendItems(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Item, SendItemsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GonetService_ServiceDesc.Streams[1], GonetService_SendItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Item, SendItemsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonetService_SendItemsClient = grpc.ClientStreamingClient[Item, SendItemsResponse]

func (c *gonetServiceClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExchangeMessage, ExchangeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GonetService_ServiceDesc.Streams[2], GonetService_Exchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExchangeMessage, ExchangeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonetService_ExchangeClient = grpc.BidiStreamingClient[ExchangeMessage, ExchangeMessage]

// GonetServiceServer is the server API for GonetService service.
// All implementations must embed UnimplementedGonetServiceServer
// for forward compatibility.
type GonetServiceServer interface {
	// 1. Unary — single request, single response
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	// 2. Server Streaming — single request, stream of responses
	ListItems(*ListItemsRequest, grpc.ServerStreamingServer[Item]) error
	// 3. Client Streaming — stream of requests, single response
	SendItems(grpc.ClientStreamingServer[Item, SendItemsResponse]) error
	// 4. Bidirectional Streaming — stream both directions simultaneously
	Exchange(grpc.BidiStreamingServer[ExchangeMessage, ExchangeMessage]) error
	mustEmbedUnimplementedGonetServiceServer()
}

// UnimplementedGonetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGonetServiceServer struct{}

func (UnimplementedGonetServiceServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedGonetServiceServer) ListItems(*ListItemsRequest, grpc.ServerStreamingServer[Item]) error {
	return status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedGonetServiceServer) SendItems(grpc.ClientStreamingServer[Item, SendItemsResponse]) error {
	return status.Error(codes.Unimplemented, "method SendItems not implemented")
}
func (UnimplementedGonetServiceServer) Exchange(grpc.BidiStreamingServer[ExchangeMessage, ExchangeMessage]) error {
	return status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedGonetServiceServer) mustEmbedUnimplementedGonetServiceServer() {}
func (UnimplementedGonetServiceServer) testEmbeddedByValue()                      {}

// UnsafeGonetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GonetServiceServer will
// result in compilation errors.
type UnsafeGonetServiceServer interface {
	mustEmbedUnimplementedGonetServiceServer()
}

func RegisterGonetServiceServer(s grpc.ServiceRegistrar, srv GonetServiceServer) {
	// If the following call panics, it indicates UnimplementedGonetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GonetService_ServiceDesc, srv)
}

func _GonetService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GonetServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GonetService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GonetServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GonetService_ListItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GonetServiceServer).ListItems(m, &grpc.GenericServerStream[ListItemsRequest, Item]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonetService_ListItemsServer = grpc.ServerStreamingServer[Item]

func _GonetService_SendItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GonetServiceServer).SendItems(&grpc.GenericServerStream[Item, SendItemsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonetService_SendItemsServer = grpc.ClientStreamingServer[Item, SendItemsResponse]

func _GonetService_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GonetServiceServer).Exchange(&grpc.GenericServerStream[ExchangeMessage, ExchangeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GonetService_ExchangeServer = grpc.BidiStreamingServer[ExchangeMessage, ExchangeMessage]

// GonetService_ServiceDesc is the grpc.ServiceDesc for GonetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GonetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gonet.GonetService",
	HandlerType: (*GonetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _GonetService_GetItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListItems",
			Handler:       _GonetService_ListItems_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendItems",
			Handler:       _GonetService_SendItems_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Exchange",
			Handler:       _GonetService_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gonet.proto",
}
